import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { analyzeProject, type AnalysisResult } from '../core/analyzer/analyze.js';
import { ATHENA_DIR } from '../core/config.js';
import { ensureRules, writeKnowledge, type DocWriteReport } from '../core/knowledge/generate.js';
import { athenaDir, backupCorruptedState, buildFileIndex, readState, writeState, type AthenaState } from '../core/state/state.js';
import { exists, readTextIfExists, sha256, writeFileAtomic } from '../core/util/fs.js';
import type { FileEntry } from '../core/fs/walker.js';
import type { AgentAdapter, PlannedFileChange } from '../core/agents/adapter.js';
import { ADAPTERS, applyChanges } from '../agents/registry.js';
import { ATHENA_VERSION } from './version.js';

export interface PipelineOptions {
  root: string;
  mode: 'init' | 'analyze';
  force?: boolean;
  dryRun?: boolean;
  /** Explicit adapters; undefined = previously configured (analyze) or auto-detected (init). */
  agents?: AgentAdapter[];
  signal?: AbortSignal;
  onStage?: (stage: string) => void;
}

export interface PipelineResult {
  analysis: AnalysisResult;
  docs: DocWriteReport[];
  agentChanges: Array<{ adapter: AgentAdapter; changes: PlannedFileChange[] }>;
  state: AthenaState | null;
  notes: string[];
}

const ATHENA_GITIGNORE = [
  '# Local analysis cache — safe to delete, regenerated by `athena analyze`.',
  '# Commit the *.md knowledge files so your team and Git history share them.',
  'state.json',
  'model.json',
  'graph.json',
  'security-scan.json',
  'ai-suggestions.md',
  '.backup/',
  '.server.json',
  '.sync-ignore.json',
  '.agent-events.jsonl',
  '',
].join('\n');

/** Entries every .athena/.gitignore should carry; older projects are topped up in place. */
const GITIGNORE_ENTRIES = ['state.json', 'model.json', 'graph.json', 'security-scan.json', 'ai-suggestions.md', '.backup/', '.server.json', '.sync-ignore.json', '.agent-events.jsonl'];

async function ensureGitignoreEntries(file: string): Promise<void> {
  const existing = await readTextIfExists(file);
  if (existing === null) {
    await writeFileAtomic(file, ATHENA_GITIGNORE);
    return;
  }
  const lines = existing.split(/\r?\n/);
  const missing = GITIGNORE_ENTRIES.filter((e) => !lines.includes(e));
  if (!missing.length) return;
  await writeFileAtomic(file, `${existing.replace(/\s*$/, '')}\n${missing.join('\n')}\n`);
}

/** Include files Athena itself just wrote (agent integrations) so they don't show up as external changes. */
export async function indexWithIntegrations(root: string, files: FileEntry[], written: string[]): Promise<AthenaState['fileIndex']> {
  const index = buildFileIndex(files);
  for (const rel of written) {
    try {
      const abs = path.join(root, rel);
      const [st, buf] = await Promise.all([fs.stat(abs), fs.readFile(abs)]);
      index[rel] = { h: sha256(buf).slice(0, 16), s: st.size, m: Math.floor(st.mtimeMs) };
    } catch {
      /* removed or unreadable — leave as analyzed */
    }
  }
  return index;
}

/** Build the next state.json from an analysis and the documents written for it. */
export function composeState(input: { prevState: AthenaState | null; analysis: AnalysisResult; docs: DocWriteReport[]; agents: AthenaState['agents']; fileIndex: AthenaState['fileIndex'] }): AthenaState {
  const { prevState, analysis, docs } = input;
  const now = new Date().toISOString();
  const documents: AthenaState['documents'] = {};
  for (const d of docs) {
    const before = prevState?.documents[d.id];
    documents[d.id] = {
      file: d.file,
      blocks: d.blocks,
      lastGeneratedAt: now,
      lastChangedAt: d.status === 'unchanged' && before ? before.lastChangedAt : now,
      contentHash: d.contentHash,
      preservedModified: d.preservedModified,
    };
  }
  return {
    schemaVersion: 1,
    athenaVersion: ATHENA_VERSION,
    projectName: analysis.model.name,
    createdAt: prevState?.createdAt ?? now,
    analyzedAt: now,
    analysisDurationMs: analysis.durationMs,
    git: { isRepo: analysis.model.git.isRepo, head: analysis.model.git.head, branch: analysis.model.git.branch },
    fileIndex: input.fileIndex,
    documents,
    detectors: analysis.detectorVersions,
    agents: input.agents,
    warnings: analysis.model.warnings,
  };
}

/** Default adapter selection for init: agents detected in the project, plus the cross-agent AGENTS.md. */
export async function autoSelectAdapters(root: string): Promise<AgentAdapter[]> {
  const selected: AgentAdapter[] = [];
  for (const a of ADAPTERS) {
    if (a.id === 'agents-md' || (await a.detectPresence(root)).detectedInProject) selected.push(a);
  }
  return selected;
}

export async function runPipeline(opts: PipelineOptions): Promise<PipelineResult> {
  const root = opts.root;
  const finalDir = athenaDir(root);
  const notes: string[] = [];

  const prev = await readState(finalDir);
  if (prev.kind === 'corrupted' && !opts.dryRun) {
    const backup = await backupCorruptedState(finalDir);
    notes.push(`state.json was corrupted (${prev.reason}); ${backup ? `moved to ${path.relative(root, backup)}` : 'it will be replaced'} and rebuilt.`);
  }
  const prevState = prev.kind === 'ok' ? prev.state : null;

  opts.onStage?.('analyze');
  const analysis = await analyzeProject(root, { signal: opts.signal, onStage: (s) => opts.onStage?.(s), reuse: prevState?.fileIndex });
  opts.signal?.throwIfAborted();

  const adapters = opts.agents ?? (prevState ? ADAPTERS.filter((a) => prevState.agents[a.id]?.configured) : await autoSelectAdapters(root));

  if (opts.dryRun) {
    const agentChanges = [];
    for (const adapter of adapters) agentChanges.push({ adapter, changes: await adapter.plan({ root, projectName: analysis.model.name }) });
    return { analysis, docs: [], agentChanges, state: null, notes };
  }

  // A fresh init builds into a temp directory and swaps it in, so an interrupted
  // run never leaves a half-written .athena/.
  const fresh = !(await exists(finalDir));
  const workDir = fresh ? path.join(root, `${ATHENA_DIR}.tmp-${crypto.randomBytes(4).toString('hex')}`) : finalDir;

  let docs: DocWriteReport[];
  try {
    opts.onStage?.('write');
    await fs.mkdir(workDir, { recursive: true });
    const previousBlocks = prevState ? Object.fromEntries(Object.entries(prevState.documents).map(([k, v]) => [k, v.blocks])) : undefined;
    docs = await writeKnowledge(workDir, analysis.model, { force: opts.force, previousBlocks });
    docs.push(await ensureRules(workDir, analysis.model));
    await writeFileAtomic(path.join(workDir, 'model.json'), `${JSON.stringify(analysis.model, null, 2)}\n`);
    await ensureGitignoreEntries(path.join(workDir, '.gitignore'));
    opts.signal?.throwIfAborted();
    if (fresh) await fs.rename(workDir, finalDir);
  } catch (err) {
    if (fresh) await fs.rm(workDir, { recursive: true, force: true }).catch(() => {});
    throw err;
  }

  opts.onStage?.('agents');
  const agentChanges: PipelineResult['agentChanges'] = [];
  const agentsState: AthenaState['agents'] = { ...(prevState?.agents ?? {}) };
  for (const adapter of adapters) {
    try {
      const planned = await adapter.plan({ root, projectName: analysis.model.name });
      await applyChanges(root, planned);
      agentChanges.push({ adapter, changes: planned });
      agentsState[adapter.id] = { configured: true, files: planned.map((p) => p.path), configuredAt: new Date().toISOString() };
    } catch (err) {
      notes.push(`${adapter.displayName} integration not configured: ${(err as Error).message}`);
    }
  }

  const state = composeState({
    prevState,
    analysis,
    docs,
    agents: agentsState,
    fileIndex: await indexWithIntegrations(root, analysis.files, agentChanges.flatMap((a) => a.changes.map((c) => c.path))),
  });
  await writeState(finalDir, state);
  return { analysis, docs, agentChanges, state, notes };
}
