import path from 'node:path';
import type { ProjectModel } from '../model/project-model.js';
import { redact } from '../security/secrets.js';
import { readTextIfExists, sha256, writeFileAtomic } from '../util/fs.js';
import { KNOWLEDGE_DOCS, type GeneratedDocId } from './documents.js';
import { LEGEND } from './md.js';
import { mergeDocument, renderBlock, type Section } from './managed-blocks.js';
import { renderProject } from './renderers/project.js';
import { renderArchitecture } from './renderers/architecture.js';
import { renderApi, renderAuth, renderDatabase } from './renderers/data.js';
import { renderSecurity } from './renderers/security.js';
import { renderCodeReview, renderDebugging, renderPerformance, renderTesting } from './renderers/quality.js';
import { renderDeployment } from './renderers/deployment.js';
import { seedRules } from './rules-seed.js';
import { loadScanFromDir, type SecurityScan } from '../model/security-scan.js';

export interface KnowledgeExtras {
  /** Latest dependency/secret scan, when one has been run. */
  securityScan?: SecurityScan | null;
}

export const RENDERERS: Record<GeneratedDocId, (m: ProjectModel, extras: KnowledgeExtras) => Section[]> = {
  project: renderProject,
  architecture: renderArchitecture,
  database: renderDatabase,
  api: renderApi,
  auth: renderAuth,
  security: renderSecurity,
  testing: renderTesting,
  debugging: renderDebugging,
  performance: renderPerformance,
  'code-review': renderCodeReview,
  deployment: renderDeployment,
};

export const DEVELOPER_NOTES_HEADING = '## Developer Notes';

export type DocWriteStatus = 'created' | 'updated' | 'unchanged';

export interface DocWriteReport {
  id: string;
  file: string;
  status: DocWriteStatus;
  blocks: string[];
  /** Blocks not regenerated because the developer edited them. */
  preservedModified: string[];
  contentHash: string;
}

export interface WriteKnowledgeOptions {
  force?: boolean;
  /** Block ids per doc id from the previous state (to respect deliberately deleted blocks). */
  previousBlocks?: Record<string, string[]>;
  /** Restrict regeneration to these docs (used by incremental sync later). */
  only?: GeneratedDocId[];
}

export function renderSections(id: GeneratedDocId, model: ProjectModel, extras: KnowledgeExtras = {}): Section[] {
  const doc = KNOWLEDGE_DOCS.find((d) => d.id === id)!;
  const about: Section = {
    id: 'about',
    content: [
      `> **Purpose:** ${doc.purpose}`,
      '>',
      '> Generated by Athena from repository analysis. Content between `athena:generated` markers is refreshed by `athena analyze`; if you edit inside a marker, Athena keeps your edit and stops refreshing that section (use `--force` to regenerate). Everything outside the markers is yours.',
      '>',
      `> ${LEGEND}`,
    ].join('\n'),
  };
  // Redact generated content only — developer-authored text is never rewritten.
  return [about, ...RENDERERS[id](model, extras)].map((s) => ({ id: s.id, content: redact(s.content) }));
}

export function composeNewDocument(id: GeneratedDocId, sections: Section[]): string {
  const doc = KNOWLEDGE_DOCS.find((d) => d.id === id)!;
  return [
    `# ${doc.title}`,
    '',
    sections.map((s) => renderBlock(s)).join('\n\n'),
    '',
    DEVELOPER_NOTES_HEADING,
    '',
    '<!-- Knowledge Athena cannot detect: decisions, conventions, known issues, gotchas. Athena never modifies this section. -->',
    '',
  ].join('\n');
}

export interface DocPlan {
  id: GeneratedDocId;
  file: string;
  status: DocWriteStatus;
  /** Current file content (null if missing). */
  before: string | null;
  /** Content after regeneration. Equal to `before` when unchanged. */
  after: string;
  blocks: string[];
  /** Generated sections whose content would change or be added. */
  changedBlocks: string[];
  preservedModified: string[];
}

/** Compute regenerated documents without writing anything. */
export async function planKnowledge(athenaDir: string, model: ProjectModel, opts: WriteKnowledgeOptions = {}): Promise<DocPlan[]> {
  const plans: DocPlan[] = [];
  // Security scan results live beside the knowledge files and are rendered into security.md.
  const extras: KnowledgeExtras = { securityScan: await loadScanFromDir(athenaDir) };
  const ids = (Object.keys(RENDERERS) as GeneratedDocId[]).filter((id) => !opts.only || opts.only.includes(id));
  for (const id of ids) {
    const doc = KNOWLEDGE_DOCS.find((d) => d.id === id)!;
    const sections = renderSections(id, model, extras);
    const before = await readTextIfExists(path.join(athenaDir, doc.file));
    if (before === null) {
      plans.push({ id, file: doc.file, status: 'created', before, after: composeNewDocument(id, sections), blocks: sections.map((s) => s.id), changedBlocks: sections.map((s) => s.id), preservedModified: [] });
      continue;
    }
    const merged = mergeDocument(before, sections, { force: opts.force, previouslyKnown: opts.previousBlocks?.[id], insertBefore: DEVELOPER_NOTES_HEADING });
    plans.push({
      id,
      file: doc.file,
      status: merged.changed ? 'updated' : 'unchanged',
      before,
      after: merged.text,
      blocks: sections.map((s) => s.id),
      changedBlocks: [...merged.updated, ...merged.added],
      preservedModified: merged.preservedModified,
    });
  }
  return plans;
}

export async function writePlannedKnowledge(athenaDir: string, plans: DocPlan[]): Promise<DocWriteReport[]> {
  const reports: DocWriteReport[] = [];
  for (const p of plans) {
    if (p.status !== 'unchanged') await writeFileAtomic(path.join(athenaDir, p.file), p.after);
    reports.push({ id: p.id, file: p.file, status: p.status, blocks: p.blocks, preservedModified: p.preservedModified, contentHash: sha256(p.after).slice(0, 16) });
  }
  return reports;
}

export async function writeKnowledge(athenaDir: string, model: ProjectModel, opts: WriteKnowledgeOptions = {}): Promise<DocWriteReport[]> {
  return writePlannedKnowledge(athenaDir, await planKnowledge(athenaDir, model, opts));
}

/** Create rules.md only if it does not exist. Never regenerated. */
export async function ensureRules(athenaDir: string, model: ProjectModel): Promise<DocWriteReport> {
  const file = path.join(athenaDir, 'rules.md');
  const existing = await readTextIfExists(file);
  if (existing !== null) return { id: 'rules', file: 'rules.md', status: 'unchanged', blocks: [], preservedModified: [], contentHash: sha256(existing).slice(0, 16) };
  const text = seedRules(model);
  await writeFileAtomic(file, text);
  return { id: 'rules', file: 'rules.md', status: 'created', blocks: [], preservedModified: [], contentHash: sha256(text).slice(0, 16) };
}
