/**
 * Known dependency → capability catalog. Matching a dependency name here yields a
 * DETECTED fact ("X is a declared dependency"), never a claim about *how* it is used.
 */

export type CatalogKind =
  | { type: 'framework'; category: 'frontend' | 'backend' | 'fullstack' | 'mobile' | 'desktop' | 'orm' | 'other' }
  | { type: 'database'; kind: 'engine' | 'orm' | 'driver' }
  | { type: 'auth'; kind: 'library' | 'provider' | 'hashing' | 'token' }
  | { type: 'cache' }
  | { type: 'queue' }
  | { type: 'observability' }
  | { type: 'securityControl' }
  | { type: 'securityTooling' }
  | { type: 'testing' };

export interface CatalogEntry {
  name: string;
  kind: CatalogKind;
  /** Config/marker files that corroborate usage (raises confidence). */
  markers?: RegExp[];
}

type Eco = 'npm' | 'python' | 'go' | 'cargo' | 'maven' | 'composer' | 'nuget' | 'gem' | 'pub' | 'hex';

const fw = (category: Extract<CatalogKind, { type: 'framework' }>['category']): CatalogKind => ({ type: 'framework', category });
const db = (kind: 'engine' | 'orm' | 'driver'): CatalogKind => ({ type: 'database', kind });
const auth = (kind: 'library' | 'provider' | 'hashing' | 'token'): CatalogKind => ({ type: 'auth', kind });
const CACHE: CatalogKind = { type: 'cache' };
const QUEUE: CatalogKind = { type: 'queue' };
const OBS: CatalogKind = { type: 'observability' };
const SEC: CatalogKind = { type: 'securityControl' };
const SECTOOL: CatalogKind = { type: 'securityTooling' };
const TEST: CatalogKind = { type: 'testing' };

export const CATALOG: Record<Eco, Record<string, CatalogEntry>> = {
  npm: {
    next: { name: 'Next.js', kind: fw('fullstack'), markers: [/(^|\/)next\.config\.(js|mjs|cjs|ts)$/] },
    react: { name: 'React', kind: fw('frontend') },
    vue: { name: 'Vue', kind: fw('frontend') },
    nuxt: { name: 'Nuxt', kind: fw('fullstack'), markers: [/(^|\/)nuxt\.config\.(js|ts|mjs)$/] },
    '@angular/core': { name: 'Angular', kind: fw('frontend'), markers: [/(^|\/)angular\.json$/] },
    svelte: { name: 'Svelte', kind: fw('frontend') },
    '@sveltejs/kit': { name: 'SvelteKit', kind: fw('fullstack'), markers: [/(^|\/)svelte\.config\.(js|ts)$/] },
    'solid-js': { name: 'SolidJS', kind: fw('frontend') },
    astro: { name: 'Astro', kind: fw('fullstack'), markers: [/(^|\/)astro\.config\.(mjs|ts|js)$/] },
    '@remix-run/react': { name: 'Remix', kind: fw('fullstack') },
    '@tanstack/react-start': { name: 'TanStack Start', kind: fw('fullstack') },
    '@tanstack/solid-start': { name: 'TanStack Start', kind: fw('fullstack') },
    '@tanstack/react-router': { name: 'TanStack Router', kind: fw('frontend') },
    '@tanstack/react-query': { name: 'TanStack Query', kind: fw('frontend') },
    '@vercel/node': { name: 'Vercel Functions (Node)', kind: fw('backend') },
    'react-router': { name: 'React Router', kind: fw('frontend') },
    vite: { name: 'Vite', kind: fw('other'), markers: [/(^|\/)vite\.config\.(js|ts|mjs)$/] },
    'react-native': { name: 'React Native', kind: fw('mobile') },
    expo: { name: 'Expo', kind: fw('mobile'), markers: [/(^|\/)app\.json$/] },
    electron: { name: 'Electron', kind: fw('desktop') },
    '@tauri-apps/api': { name: 'Tauri', kind: fw('desktop') },
    express: { name: 'Express', kind: fw('backend') },
    fastify: { name: 'Fastify', kind: fw('backend') },
    koa: { name: 'Koa', kind: fw('backend') },
    hono: { name: 'Hono', kind: fw('backend') },
    '@nestjs/core': { name: 'NestJS', kind: fw('backend'), markers: [/(^|\/)nest-cli\.json$/] },
    '@trpc/server': { name: 'tRPC', kind: fw('backend') },
    '@apollo/server': { name: 'Apollo Server', kind: fw('backend') },
    'apollo-server': { name: 'Apollo Server', kind: fw('backend') },
    graphql: { name: 'GraphQL', kind: fw('other') },
    tailwindcss: { name: 'Tailwind CSS', kind: fw('frontend') },
    prisma: { name: 'Prisma', kind: db('orm'), markers: [/(^|\/)schema\.prisma$/] },
    '@prisma/client': { name: 'Prisma', kind: db('orm'), markers: [/(^|\/)schema\.prisma$/] },
    'drizzle-orm': { name: 'Drizzle ORM', kind: db('orm'), markers: [/(^|\/)drizzle\.config\.(ts|js)$/] },
    typeorm: { name: 'TypeORM', kind: db('orm') },
    sequelize: { name: 'Sequelize', kind: db('orm') },
    mongoose: { name: 'Mongoose', kind: db('orm') },
    knex: { name: 'Knex', kind: db('orm') },
    kysely: { name: 'Kysely', kind: db('orm') },
    '@mikro-orm/core': { name: 'MikroORM', kind: db('orm') },
    pg: { name: 'PostgreSQL (pg driver)', kind: db('driver') },
    postgres: { name: 'PostgreSQL (postgres.js driver)', kind: db('driver') },
    mysql: { name: 'MySQL driver', kind: db('driver') },
    mysql2: { name: 'MySQL driver', kind: db('driver') },
    'better-sqlite3': { name: 'SQLite (better-sqlite3)', kind: db('driver') },
    sqlite3: { name: 'SQLite driver', kind: db('driver') },
    mongodb: { name: 'MongoDB driver', kind: db('driver') },
    '@supabase/supabase-js': { name: 'Supabase', kind: db('driver') },
    firebase: { name: 'Firebase', kind: db('driver') },
    'firebase-admin': { name: 'Firebase Admin', kind: db('driver') },
    '@planetscale/database': { name: 'PlanetScale driver', kind: db('driver') },
    '@neondatabase/serverless': { name: 'Neon serverless driver', kind: db('driver') },
    'next-auth': { name: 'NextAuth.js / Auth.js', kind: auth('library') },
    '@auth/core': { name: 'Auth.js', kind: auth('library') },
    'better-auth': { name: 'Better Auth', kind: auth('library') },
    passport: { name: 'Passport', kind: auth('library') },
    lucia: { name: 'Lucia', kind: auth('library') },
    '@clerk/nextjs': { name: 'Clerk', kind: auth('provider') },
    '@clerk/clerk-react': { name: 'Clerk', kind: auth('provider') },
    '@auth0/nextjs-auth0': { name: 'Auth0', kind: auth('provider') },
    'auth0': { name: 'Auth0', kind: auth('provider') },
    '@supabase/auth-helpers-nextjs': { name: 'Supabase Auth', kind: auth('provider') },
    '@supabase/ssr': { name: 'Supabase SSR Auth', kind: auth('provider') },
    'firebase-auth': { name: 'Firebase Auth', kind: auth('provider') },
    jsonwebtoken: { name: 'jsonwebtoken (JWT)', kind: auth('token') },
    jose: { name: 'jose (JWT/JWE)', kind: auth('token') },
    'express-session': { name: 'express-session', kind: auth('library') },
    'iron-session': { name: 'iron-session', kind: auth('library') },
    bcrypt: { name: 'bcrypt', kind: auth('hashing') },
    bcryptjs: { name: 'bcryptjs', kind: auth('hashing') },
    argon2: { name: 'argon2', kind: auth('hashing') },
    '@node-rs/argon2': { name: 'argon2', kind: auth('hashing') },
    ioredis: { name: 'Redis (ioredis)', kind: CACHE },
    redis: { name: 'Redis client', kind: CACHE },
    '@upstash/redis': { name: 'Upstash Redis', kind: CACHE },
    'lru-cache': { name: 'lru-cache', kind: CACHE },
    'node-cache': { name: 'node-cache', kind: CACHE },
    bullmq: { name: 'BullMQ', kind: QUEUE },
    bull: { name: 'Bull', kind: QUEUE },
    'bee-queue': { name: 'Bee-Queue', kind: QUEUE },
    amqplib: { name: 'RabbitMQ (amqplib)', kind: QUEUE },
    kafkajs: { name: 'Kafka (kafkajs)', kind: QUEUE },
    '@aws-sdk/client-sqs': { name: 'AWS SQS', kind: QUEUE },
    inngest: { name: 'Inngest', kind: QUEUE },
    '@trigger.dev/sdk': { name: 'Trigger.dev', kind: QUEUE },
    '@sentry/node': { name: 'Sentry', kind: OBS },
    '@sentry/nextjs': { name: 'Sentry', kind: OBS },
    '@sentry/react': { name: 'Sentry', kind: OBS },
    pino: { name: 'Pino logger', kind: OBS },
    winston: { name: 'Winston logger', kind: OBS },
    '@opentelemetry/api': { name: 'OpenTelemetry', kind: OBS },
    'dd-trace': { name: 'Datadog APM', kind: OBS },
    helmet: { name: 'helmet', kind: SEC },
    cors: { name: 'cors', kind: SEC },
    '@fastify/cors': { name: '@fastify/cors', kind: SEC },
    '@fastify/helmet': { name: '@fastify/helmet', kind: SEC },
    csurf: { name: 'csurf (deprecated)', kind: SEC },
    'csrf-csrf': { name: 'csrf-csrf', kind: SEC },
    'express-rate-limit': { name: 'express-rate-limit', kind: SEC },
    '@fastify/rate-limit': { name: '@fastify/rate-limit', kind: SEC },
    zod: { name: 'zod (schema validation)', kind: SEC },
    joi: { name: 'joi (schema validation)', kind: SEC },
    yup: { name: 'yup (schema validation)', kind: SEC },
    'class-validator': { name: 'class-validator', kind: SEC },
    dompurify: { name: 'DOMPurify', kind: SEC },
    'isomorphic-dompurify': { name: 'DOMPurify', kind: SEC },
    eslint: { name: 'ESLint', kind: SECTOOL },
    'eslint-plugin-security': { name: 'eslint-plugin-security', kind: SECTOOL },
    snyk: { name: 'Snyk', kind: SECTOOL },
    jest: { name: 'Jest', kind: TEST },
    vitest: { name: 'Vitest', kind: TEST },
    mocha: { name: 'Mocha', kind: TEST },
    ava: { name: 'AVA', kind: TEST },
    '@playwright/test': { name: 'Playwright', kind: TEST },
    cypress: { name: 'Cypress', kind: TEST },
    '@testing-library/react': { name: 'Testing Library', kind: TEST },
    supertest: { name: 'Supertest', kind: TEST },
    detox: { name: 'Detox', kind: TEST },
  },
  python: {
    django: { name: 'Django', kind: fw('fullstack'), markers: [/(^|\/)manage\.py$/] },
    djangorestframework: { name: 'Django REST Framework', kind: fw('backend') },
    fastapi: { name: 'FastAPI', kind: fw('backend') },
    flask: { name: 'Flask', kind: fw('backend') },
    starlette: { name: 'Starlette', kind: fw('backend') },
    litestar: { name: 'Litestar', kind: fw('backend') },
    tornado: { name: 'Tornado', kind: fw('backend') },
    aiohttp: { name: 'aiohttp', kind: fw('backend') },
    streamlit: { name: 'Streamlit', kind: fw('frontend') },
    pydantic: { name: 'Pydantic (validation)', kind: SEC },
    sqlalchemy: { name: 'SQLAlchemy', kind: db('orm') },
    sqlmodel: { name: 'SQLModel', kind: db('orm') },
    'tortoise-orm': { name: 'Tortoise ORM', kind: db('orm') },
    peewee: { name: 'Peewee', kind: db('orm') },
    alembic: { name: 'Alembic migrations', kind: db('orm') },
    'psycopg2': { name: 'PostgreSQL (psycopg2)', kind: db('driver') },
    'psycopg2-binary': { name: 'PostgreSQL (psycopg2)', kind: db('driver') },
    psycopg: { name: 'PostgreSQL (psycopg 3)', kind: db('driver') },
    asyncpg: { name: 'PostgreSQL (asyncpg)', kind: db('driver') },
    pymysql: { name: 'MySQL (PyMySQL)', kind: db('driver') },
    mysqlclient: { name: 'MySQL (mysqlclient)', kind: db('driver') },
    pymongo: { name: 'MongoDB (pymongo)', kind: db('driver') },
    motor: { name: 'MongoDB (motor)', kind: db('driver') },
    'django-allauth': { name: 'django-allauth', kind: auth('library') },
    'djangorestframework-simplejwt': { name: 'Simple JWT (DRF)', kind: auth('token') },
    pyjwt: { name: 'PyJWT', kind: auth('token') },
    'python-jose': { name: 'python-jose', kind: auth('token') },
    authlib: { name: 'Authlib', kind: auth('library') },
    'flask-login': { name: 'Flask-Login', kind: auth('library') },
    'fastapi-users': { name: 'FastAPI Users', kind: auth('library') },
    passlib: { name: 'passlib', kind: auth('hashing') },
    bcrypt: { name: 'bcrypt', kind: auth('hashing') },
    'argon2-cffi': { name: 'argon2-cffi', kind: auth('hashing') },
    redis: { name: 'Redis client', kind: CACHE },
    'django-redis': { name: 'django-redis', kind: CACHE },
    celery: { name: 'Celery', kind: QUEUE },
    rq: { name: 'RQ', kind: QUEUE },
    dramatiq: { name: 'Dramatiq', kind: QUEUE },
    'sentry-sdk': { name: 'Sentry', kind: OBS },
    structlog: { name: 'structlog', kind: OBS },
    'opentelemetry-api': { name: 'OpenTelemetry', kind: OBS },
    'django-cors-headers': { name: 'django-cors-headers', kind: SEC },
    bandit: { name: 'Bandit', kind: SECTOOL },
    'pip-audit': { name: 'pip-audit', kind: SECTOOL },
    safety: { name: 'Safety', kind: SECTOOL },
    ruff: { name: 'Ruff', kind: SECTOOL },
    pytest: { name: 'pytest', kind: TEST },
    'pytest-django': { name: 'pytest-django', kind: TEST },
    hypothesis: { name: 'Hypothesis', kind: TEST },
    playwright: { name: 'Playwright', kind: TEST },
  },
  go: {
    'github.com/gin-gonic/gin': { name: 'Gin', kind: fw('backend') },
    'github.com/labstack/echo/v4': { name: 'Echo', kind: fw('backend') },
    'github.com/gofiber/fiber/v2': { name: 'Fiber', kind: fw('backend') },
    'github.com/gofiber/fiber/v3': { name: 'Fiber', kind: fw('backend') },
    'github.com/go-chi/chi/v5': { name: 'chi', kind: fw('backend') },
    'github.com/gorilla/mux': { name: 'gorilla/mux', kind: fw('backend') },
    'google.golang.org/grpc': { name: 'gRPC', kind: fw('backend') },
    'gorm.io/gorm': { name: 'GORM', kind: db('orm') },
    'entgo.io/ent': { name: 'ent', kind: db('orm') },
    'github.com/jmoiron/sqlx': { name: 'sqlx', kind: db('driver') },
    'github.com/jackc/pgx/v5': { name: 'PostgreSQL (pgx)', kind: db('driver') },
    'github.com/lib/pq': { name: 'PostgreSQL (lib/pq)', kind: db('driver') },
    'github.com/go-sql-driver/mysql': { name: 'MySQL driver', kind: db('driver') },
    'go.mongodb.org/mongo-driver': { name: 'MongoDB driver', kind: db('driver') },
    'github.com/golang-migrate/migrate/v4': { name: 'golang-migrate', kind: db('orm') },
    'github.com/golang-jwt/jwt/v5': { name: 'golang-jwt', kind: auth('token') },
    'golang.org/x/crypto': { name: 'x/crypto (may include bcrypt/argon2)', kind: auth('hashing') },
    'golang.org/x/oauth2': { name: 'x/oauth2', kind: auth('library') },
    'github.com/redis/go-redis/v9': { name: 'Redis (go-redis)', kind: CACHE },
    'github.com/hibiken/asynq': { name: 'Asynq', kind: QUEUE },
    'github.com/segmentio/kafka-go': { name: 'Kafka (kafka-go)', kind: QUEUE },
    'go.uber.org/zap': { name: 'zap logger', kind: OBS },
    'github.com/rs/zerolog': { name: 'zerolog', kind: OBS },
    'github.com/getsentry/sentry-go': { name: 'Sentry', kind: OBS },
    'github.com/stretchr/testify': { name: 'testify', kind: TEST },
  },
  cargo: {
    axum: { name: 'Axum', kind: fw('backend') },
    'actix-web': { name: 'Actix Web', kind: fw('backend') },
    rocket: { name: 'Rocket', kind: fw('backend') },
    warp: { name: 'warp', kind: fw('backend') },
    tonic: { name: 'tonic (gRPC)', kind: fw('backend') },
    leptos: { name: 'Leptos', kind: fw('fullstack') },
    tauri: { name: 'Tauri', kind: fw('desktop') },
    diesel: { name: 'Diesel', kind: db('orm') },
    sqlx: { name: 'SQLx', kind: db('driver') },
    'sea-orm': { name: 'SeaORM', kind: db('orm') },
    'tokio-postgres': { name: 'PostgreSQL (tokio-postgres)', kind: db('driver') },
    mongodb: { name: 'MongoDB driver', kind: db('driver') },
    jsonwebtoken: { name: 'jsonwebtoken', kind: auth('token') },
    argon2: { name: 'argon2', kind: auth('hashing') },
    bcrypt: { name: 'bcrypt', kind: auth('hashing') },
    oauth2: { name: 'oauth2', kind: auth('library') },
    redis: { name: 'Redis client', kind: CACHE },
    moka: { name: 'moka cache', kind: CACHE },
    lapin: { name: 'RabbitMQ (lapin)', kind: QUEUE },
    rdkafka: { name: 'Kafka (rdkafka)', kind: QUEUE },
    tracing: { name: 'tracing', kind: OBS },
    sentry: { name: 'Sentry', kind: OBS },
    'tower-http': { name: 'tower-http (may include CORS)', kind: SEC },
  },
  maven: {
    'spring-boot-starter-web': { name: 'Spring Boot (Web)', kind: fw('backend') },
    'spring-boot-starter-webflux': { name: 'Spring WebFlux', kind: fw('backend') },
    'spring-boot-starter': { name: 'Spring Boot', kind: fw('backend') },
    'spring-boot-starter-data-jpa': { name: 'Spring Data JPA', kind: db('orm') },
    'spring-boot-starter-data-mongodb': { name: 'Spring Data MongoDB', kind: db('orm') },
    'hibernate-core': { name: 'Hibernate', kind: db('orm') },
    'mybatis': { name: 'MyBatis', kind: db('orm') },
    postgresql: { name: 'PostgreSQL JDBC', kind: db('driver') },
    'mysql-connector-j': { name: 'MySQL JDBC', kind: db('driver') },
    'flyway-core': { name: 'Flyway', kind: db('orm') },
    'liquibase-core': { name: 'Liquibase', kind: db('orm') },
    'spring-boot-starter-security': { name: 'Spring Security', kind: auth('library') },
    'spring-boot-starter-oauth2-resource-server': { name: 'Spring OAuth2 Resource Server', kind: auth('library') },
    'spring-boot-starter-oauth2-client': { name: 'Spring OAuth2 Client', kind: auth('library') },
    'jjwt-api': { name: 'JJWT', kind: auth('token') },
    'spring-boot-starter-data-redis': { name: 'Spring Data Redis', kind: CACHE },
    'spring-boot-starter-cache': { name: 'Spring Cache', kind: CACHE },
    'spring-kafka': { name: 'Spring Kafka', kind: QUEUE },
    'spring-boot-starter-amqp': { name: 'Spring AMQP', kind: QUEUE },
    'spring-boot-starter-actuator': { name: 'Spring Boot Actuator', kind: OBS },
    'spring-boot-starter-validation': { name: 'Bean Validation', kind: SEC },
    'spring-boot-starter-test': { name: 'Spring Boot Test', kind: TEST },
    'junit-jupiter': { name: 'JUnit 5', kind: TEST },
    junit: { name: 'JUnit', kind: TEST },
    'mockito-core': { name: 'Mockito', kind: TEST },
    testcontainers: { name: 'Testcontainers', kind: TEST },
  },
  composer: {
    'laravel/framework': { name: 'Laravel', kind: fw('fullstack'), markers: [/(^|\/)artisan$/] },
    'symfony/framework-bundle': { name: 'Symfony', kind: fw('fullstack') },
    'slim/slim': { name: 'Slim', kind: fw('backend') },
    'doctrine/orm': { name: 'Doctrine ORM', kind: db('orm') },
    'laravel/sanctum': { name: 'Laravel Sanctum', kind: auth('library') },
    'laravel/passport': { name: 'Laravel Passport', kind: auth('library') },
    'tymon/jwt-auth': { name: 'jwt-auth', kind: auth('token') },
    'firebase/php-jwt': { name: 'php-jwt', kind: auth('token') },
    'predis/predis': { name: 'Predis (Redis)', kind: CACHE },
    'sentry/sentry-laravel': { name: 'Sentry', kind: OBS },
    'phpunit/phpunit': { name: 'PHPUnit', kind: TEST },
    'pestphp/pest': { name: 'Pest', kind: TEST },
  },
  nuget: {
    'Microsoft.AspNetCore.App': { name: 'ASP.NET Core', kind: fw('backend') },
    'Microsoft.EntityFrameworkCore': { name: 'Entity Framework Core', kind: db('orm') },
    'Npgsql.EntityFrameworkCore.PostgreSQL': { name: 'PostgreSQL (Npgsql EF)', kind: db('driver') },
    'Microsoft.EntityFrameworkCore.SqlServer': { name: 'SQL Server (EF)', kind: db('driver') },
    Dapper: { name: 'Dapper', kind: db('orm') },
    'Microsoft.AspNetCore.Identity.EntityFrameworkCore': { name: 'ASP.NET Core Identity', kind: auth('library') },
    'Microsoft.AspNetCore.Authentication.JwtBearer': { name: 'JWT Bearer auth', kind: auth('token') },
    'StackExchange.Redis': { name: 'StackExchange.Redis', kind: CACHE },
    'MassTransit': { name: 'MassTransit', kind: QUEUE },
    Serilog: { name: 'Serilog', kind: OBS },
    xunit: { name: 'xUnit', kind: TEST },
    NUnit: { name: 'NUnit', kind: TEST },
    MSTest: { name: 'MSTest', kind: TEST },
  },
  gem: {
    rails: { name: 'Ruby on Rails', kind: fw('fullstack'), markers: [/(^|\/)config\/routes\.rb$/] },
    sinatra: { name: 'Sinatra', kind: fw('backend') },
    'activerecord': { name: 'ActiveRecord', kind: db('orm') },
    pg: { name: 'PostgreSQL (pg gem)', kind: db('driver') },
    mysql2: { name: 'MySQL (mysql2 gem)', kind: db('driver') },
    devise: { name: 'Devise', kind: auth('library') },
    omniauth: { name: 'OmniAuth', kind: auth('library') },
    pundit: { name: 'Pundit (authorization)', kind: auth('library') },
    cancancan: { name: 'CanCanCan (authorization)', kind: auth('library') },
    jwt: { name: 'ruby-jwt', kind: auth('token') },
    bcrypt: { name: 'bcrypt', kind: auth('hashing') },
    redis: { name: 'Redis client', kind: CACHE },
    sidekiq: { name: 'Sidekiq', kind: QUEUE },
    'sentry-ruby': { name: 'Sentry', kind: OBS },
    brakeman: { name: 'Brakeman', kind: SECTOOL },
    'bundler-audit': { name: 'bundler-audit', kind: SECTOOL },
    rspec: { name: 'RSpec', kind: TEST },
    'rspec-rails': { name: 'RSpec Rails', kind: TEST },
    minitest: { name: 'Minitest', kind: TEST },
  },
  pub: {
    flutter: { name: 'Flutter', kind: fw('mobile') },
    firebase_core: { name: 'Firebase', kind: db('driver') },
    cloud_firestore: { name: 'Cloud Firestore', kind: db('driver') },
    sqflite: { name: 'SQLite (sqflite)', kind: db('driver') },
    drift: { name: 'Drift', kind: db('orm') },
    firebase_auth: { name: 'Firebase Auth', kind: auth('provider') },
    supabase_flutter: { name: 'Supabase', kind: db('driver') },
    flutter_test: { name: 'flutter_test', kind: TEST },
    integration_test: { name: 'integration_test', kind: TEST },
    sentry_flutter: { name: 'Sentry', kind: OBS },
  },
  hex: {
    phoenix: { name: 'Phoenix', kind: fw('fullstack') },
    ecto_sql: { name: 'Ecto', kind: db('orm') },
    postgrex: { name: 'PostgreSQL (Postgrex)', kind: db('driver') },
    guardian: { name: 'Guardian', kind: auth('token') },
    bcrypt_elixir: { name: 'bcrypt_elixir', kind: auth('hashing') },
    oban: { name: 'Oban', kind: QUEUE },
  },
};

export function ecosystemKey(ecosystem: string): Eco | null {
  const map: Record<string, Eco> = {
    npm: 'npm', python: 'python', go: 'go', cargo: 'cargo', maven: 'maven', gradle: 'maven',
    composer: 'composer', nuget: 'nuget', rubygems: 'gem', pub: 'pub', hex: 'hex',
  };
  return map[ecosystem] ?? null;
}

/** Normalize dependency names per ecosystem (python is case/underscore insensitive). */
export function normalizeDep(ecosystem: string, dep: string): string {
  if (ecosystem === 'python') return dep.toLowerCase().replace(/_/g, '-');
  return dep;
}
