import { promises as fs } from 'node:fs';
import path from 'node:path';
import { exists, readTextIfExists } from '../../core/util/fs.js';
import { INTEGRATION_END, INTEGRATION_START, removeIntegrationBlock, upsertIntegrationBlock } from '../../core/knowledge/managed-blocks.js';
import type { IntegrationCheck, PlannedFileChange } from '../../core/agents/adapter.js';

export const OWNED_HEADER = '<!-- Generated by Athena. This file is owned by Athena and may be rewritten by `athena init`/`athena agents`. -->';

export async function planBlock(root: string, rel: string, body: string): Promise<PlannedFileChange> {
  const existing = await readTextIfExists(path.join(root, rel));
  const content = upsertIntegrationBlock(existing, body);
  return { path: rel, ownership: 'block', action: existing === null ? 'create' : existing === content ? 'unchanged' : 'update', content };
}

export async function planOwned(root: string, rel: string, content: string): Promise<PlannedFileChange> {
  const existing = await readTextIfExists(path.join(root, rel));
  if (existing !== null && !existing.includes('Generated by Athena')) {
    // Never overwrite a user file that happens to live at an Athena path.
    return { path: rel, ownership: 'owned', action: 'unchanged', content: existing };
  }
  return { path: rel, ownership: 'owned', action: existing === null ? 'create' : existing === content ? 'unchanged' : 'update', content };
}

export async function removeBlockFrom(root: string, rel: string): Promise<boolean> {
  const file = path.join(root, rel);
  const existing = await readTextIfExists(file);
  if (existing === null || !existing.includes(INTEGRATION_START)) return false;
  const next = removeIntegrationBlock(existing);
  if (next.trim() === '') await fs.rm(file);
  else await fs.writeFile(file, next, 'utf8');
  return true;
}

export async function removeOwned(root: string, rel: string): Promise<boolean> {
  const file = path.join(root, rel);
  const existing = await readTextIfExists(file);
  if (existing === null || !existing.includes('Generated by Athena')) return false;
  await fs.rm(file);
  return true;
}

export async function checkBlock(root: string, rel: string, label: string): Promise<IntegrationCheck> {
  const text = await readTextIfExists(path.join(root, rel));
  if (text === null) return { ok: false, level: 'warn', message: `${label}: ${rel} not found (run \`athena init\` or \`athena analyze\`)` };
  const s = text.indexOf(INTEGRATION_START);
  const e = text.indexOf(INTEGRATION_END);
  if (s === -1 && e === -1) return { ok: false, level: 'warn', message: `${label}: ${rel} has no Athena block` };
  if (s === -1 || e < s) return { ok: false, level: 'error', message: `${label}: ${rel} has a malformed Athena block (unmatched markers)` };
  return { ok: true, level: 'ok', message: `${label}: ${rel}` };
}

export async function anyExists(root: string, rels: string[]): Promise<string[]> {
  const found: string[] = [];
  for (const r of rels) if (await exists(path.join(root, r))) found.push(r);
  return found;
}

/**
 * Evidence that the developer uses an agent, excluding anything Athena itself created.
 * - `files`: a file counts if it exists and has content outside Athena's block/marker.
 * - `dirs`: a directory counts if it contains any entry other than Athena-owned paths.
 */
export async function userEvidence(root: string, spec: { files?: string[]; dirs?: string[]; athenaOwned?: string[] }): Promise<string[]> {
  const found: string[] = [];
  const owned = new Set(spec.athenaOwned ?? []);
  for (const rel of spec.files ?? []) {
    const text = await readTextIfExists(path.join(root, rel)).catch(() => null);
    if (text === null) continue;
    if (text.includes(OWNED_HEADER)) continue; // entirely Athena-owned
    if (removeIntegrationBlock(text).trim()) found.push(rel); // content besides Athena's block
  }
  for (const rel of spec.dirs ?? []) {
    if (await hasNonAthenaEntries(path.join(root, rel), root, owned)) found.push(rel);
  }
  return found;
}

async function hasNonAthenaEntries(dir: string, root: string, owned: Set<string>): Promise<boolean> {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return false;
  }
  for (const e of entries) {
    const abs = path.join(dir, e.name);
    const rel = path.relative(root, abs).split(path.sep).join('/');
    if (owned.has(rel)) continue;
    if (e.isDirectory()) {
      if (await hasNonAthenaEntries(abs, root, owned)) return true;
    } else return true;
  }
  return false;
}
