import { promises as fs } from 'node:fs';
import path from 'node:path';
import { readTextIfExists } from '../../core/util/fs.js';
import type { PlannedFileChange } from '../../core/agents/adapter.js';

/**
 * Athena-owned entries inside agent-owned JSON config files.
 *
 * Athena only ever adds, updates or removes entries carrying ATHENA_MARK; every
 * other hook in the file belongs to the developer and is preserved byte-for-byte
 * wherever JSON round-tripping allows.
 */
export const ATHENA_MARK = '--athena-hook';

/** The command agents run. Overridable for tests or unusual installs. */
export function hookCommand(): string {
  return process.env.ATHENA_HOOK_COMMAND?.trim() || 'athena';
}

export function hookArgs(agent: string, hook: string): string[] {
  return ['event', ATHENA_MARK, '--agent', agent, '--hook', hook];
}

export async function readJsonFile(file: string): Promise<{ data: Record<string, unknown>; existed: boolean; malformed: boolean }> {
  const text = await readTextIfExists(file);
  if (text === null) return { data: {}, existed: false, malformed: false };
  try {
    const parsed = JSON.parse(text) as unknown;
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) return { data: parsed as Record<string, unknown>, existed: true, malformed: false };
    return { data: {}, existed: true, malformed: true };
  } catch {
    return { data: {}, existed: true, malformed: true };
  }
}

export function isAthenaEntry(entry: unknown): boolean {
  return JSON.stringify(entry ?? '').includes(ATHENA_MARK);
}

export async function planJsonChange(root: string, rel: string, mutate: (data: Record<string, unknown>) => void): Promise<PlannedFileChange> {
  const file = path.join(root, rel);
  const { data, existed, malformed } = await readJsonFile(file);
  if (malformed) throw new Error(`${rel} is not valid JSON — fix it before configuring hooks`);
  const before = JSON.stringify(data);
  mutate(data);
  const content = `${JSON.stringify(data, null, 2)}\n`;
  return { path: rel, ownership: 'block', action: !existed ? 'create' : JSON.stringify(data) === before ? 'unchanged' : 'update', content };
}

/** Remove Athena entries from a JSON hooks file; deletes the file if nothing else remains. */
export async function removeJsonHooks(root: string, rel: string, strip: (data: Record<string, unknown>) => void, isEmpty: (data: Record<string, unknown>) => boolean): Promise<boolean> {
  const file = path.join(root, rel);
  const { data, existed, malformed } = await readJsonFile(file);
  if (!existed || malformed) return false;
  const before = JSON.stringify(data);
  strip(data);
  if (JSON.stringify(data) === before) return false;
  if (isEmpty(data)) await fs.rm(file, { force: true });
  else await fs.writeFile(file, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
  return true;
}

/** Drop empty containers left behind after removing Athena entries. */
export function pruneEmpty(record: Record<string, unknown>, key: string): void {
  const value = record[key];
  if (value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === 0) delete record[key];
  if (Array.isArray(value) && value.length === 0) delete record[key];
}

const SAFE_WORD = /^[A-Za-z0-9_@%+=:,./-]+$/;

/** Quote one argument for POSIX sh: single quotes, with embedded quotes as '\''. */
export function shQuote(value: string): string {
  if (value.includes('\0')) throw new Error('Hook command contains a NUL byte');
  if (value && SAFE_WORD.test(value)) return value;
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Quote one argument for a Windows .cmd file: double quotes, with % doubled so batch
 * expansion can't run. cmd has no escape for " inside quotes, so those are refused.
 */
export function cmdQuote(value: string): string {
  if (/["\r\n\0]/.test(value)) throw new Error(`Hook command cannot be quoted safely for cmd.exe: ${JSON.stringify(value)}`);
  const escaped = value.replace(/%/g, '%%');
  if (value && /^[A-Za-z0-9_@+=:,./\\-]+$/.test(value)) return escaped;
  return `"${escaped}"`;
}

/**
 * A tiny script that forwards the hook payload on stdin to `athena event`.
 * Used by agents that execute a script path rather than a command line.
 */
export function hookScript(agent: string, platform: NodeJS.Platform = process.platform): { file: string; content: string; mode: number } {
  const command = hookCommand();
  if (platform === 'win32') {
    return {
      file: 'athena-hook.cmd',
      content: ['@echo off', 'rem Generated by Athena: forwards agent hook payloads to `athena event`.', `${cmdQuote(command)} event ${ATHENA_MARK} --agent ${cmdQuote(agent)} --hook "%~1"`, 'exit /b 0', ''].join('\r\n'),
      mode: 0o644,
    };
  }
  return {
    file: 'athena-hook.sh',
    content: ['#!/bin/sh', '# Generated by Athena: forwards agent hook payloads to `athena event`.', `exec ${shQuote(command)} event ${ATHENA_MARK} --agent ${shQuote(agent)} --hook "$1"`, ''].join('\n'),
    mode: 0o755,
  };
}

/** Shared shape for MCP server registration (Claude Code's .mcp.json and Cursor's .cursor/mcp.json). */
export function athenaMcpEntry(): Record<string, unknown> {
  return { command: hookCommand(), args: ['mcp'] };
}

export function mergeMcpServers(data: Record<string, unknown>): void {
  const servers = (data.mcpServers && typeof data.mcpServers === 'object' && !Array.isArray(data.mcpServers) ? data.mcpServers : {}) as Record<string, unknown>;
  servers.athena = athenaMcpEntry();
  data.mcpServers = servers;
}

export function stripMcpServers(data: Record<string, unknown>): void {
  const servers = data.mcpServers as Record<string, unknown> | undefined;
  if (!servers) return;
  delete servers.athena;
  pruneEmpty(data, 'mcpServers');
}
