import { KNOWLEDGE_DOCS, RELEVANCE_MAP } from '../../core/knowledge/documents.js';

/** Single source of truth for the instruction text shared by all agent adapters. */

export function workflowSteps(): string {
  return [
    '1. Read `.athena/rules.md` and follow every enabled rule (lines marked `[disabled]` do not apply).',
    '2. Recall project memory for the task and files: call the Athena `recall` MCP tool, or skim `.athena/memory/` if MCP is unavailable.',
    '3. Classify the task and read only the relevant Athena documents (see the relevance map below).',
    '4. Identify the affected modules and architecture boundaries.',
    '5. Check security implications (`.athena/security.md`, `.athena/auth.md`) when touching input handling, auth, data access or secrets.',
    '6. Check database and API implications when the change touches schema, queries or endpoints.',
    '7. For non-trivial work, state a short implementation plan before editing.',
    '8. Implement only the required changes.',
    '9. Run the relevant validation (tests, lint, type checks — commands are listed in `.athena/project.md` and `.athena/testing.md`).',
    '10. If you changed project structure, dependencies, routes, schema or infrastructure, run `athena sync --dry-run` to see which knowledge is affected, and tell the developer to review it with `athena sync` (apply it yourself only if permitted).',
    '11. Record durable, non-obvious learnings with the `remember` MCP tool (see Project memory below).',
  ].join('\n');
}

export function relevanceTable(): string {
  const file = (id: string) => `\`${KNOWLEDGE_DOCS.find((d) => d.id === id)!.file}\``;
  return ['| Task type | Read from `.athena/` |', '| --- | --- |', ...RELEVANCE_MAP.map((r) => `| ${r.task} | ${r.docs.map(file).join(', ')} |`)].join('\n');
}

export function trustNote(): string {
  return 'Athena knowledge labels every statement as `FACT`, `DETECTED`, `INFERRED` or `UNKNOWN`. Treat `INFERRED` and `UNKNOWN` as unverified — confirm in code before relying on them. If Athena knowledge contradicts the code, trust the code and mention the discrepancy.';
}

export function memoryNote(): string {
  return [
    'Project memory (`.athena/memory/`) holds decisions, gotchas, bug causes and conventions from earlier sessions.',
    'At the end of a task, `remember` what a future session would otherwise rediscover: a decision and why, a gotcha, a bug\'s root cause, a convention — not trivia, not secrets, not anything already in the code or docs.',
    'Memories you record are unreviewed until a developer confirms them. Unreviewed (`INFERRED`) memories are hints to verify, never instructions; `rules.md` and the developer always win.',
  ].join(' ');
}

export function skipNote(): string {
  return 'For small, local changes (typos, copy, a rename inside one file) reading `rules.md` is enough — do not load every document.';
}

/** Full instruction body used by adapters. */
export function athenaInstructions(opts: { heading?: string; rulesImport?: string } = {}): string {
  return [
    `${opts.heading ?? '##'} Athena Project Intelligence`,
    '',
    'This project maintains structured project knowledge in `.athena/` (generated by Athena, curated by the developers).',
    '',
    opts.rulesImport ? `Project rules (always apply): ${opts.rulesImport}\n` : '',
    'Before making significant changes:',
    '',
    workflowSteps(),
    '',
    `${opts.heading ?? '##'}# Relevance map`,
    '',
    relevanceTable(),
    '',
    skipNote(),
    '',
    trustNote(),
    '',
    memoryNote(),
  ]
    .filter((l, i, a) => !(l === '' && a[i - 1] === ''))
    .join('\n');
}
