import { KNOWLEDGE_DOCS, RELEVANCE_MAP } from '../../core/knowledge/documents.js';

/** Single source of truth for the instruction text shared by all agent adapters. */

export function workflowSteps(): string {
  return [
    '1. Read `.athena/rules.md` and follow every enabled rule (lines marked `[disabled]` do not apply).',
    '2. Classify the task and read only the relevant Athena documents (see the relevance map below).',
    '3. Identify the affected modules and architecture boundaries.',
    '4. Check security implications (`.athena/security.md`, `.athena/auth.md`) when touching input handling, auth, data access or secrets.',
    '5. Check database and API implications when the change touches schema, queries or endpoints.',
    '6. For non-trivial work, state a short implementation plan before editing.',
    '7. Implement only the required changes.',
    '8. Run the relevant validation (tests, lint, type checks — commands are listed in `.athena/project.md` and `.athena/testing.md`).',
    '9. If you changed project structure, dependencies, routes, schema or infrastructure, tell the developer to run `athena analyze` (or run it yourself if permitted).',
  ].join('\n');
}

export function relevanceTable(): string {
  const file = (id: string) => `\`${KNOWLEDGE_DOCS.find((d) => d.id === id)!.file}\``;
  return ['| Task type | Read from `.athena/` |', '| --- | --- |', ...RELEVANCE_MAP.map((r) => `| ${r.task} | ${r.docs.map(file).join(', ')} |`)].join('\n');
}

export function trustNote(): string {
  return 'Athena knowledge labels every statement as `FACT`, `DETECTED`, `INFERRED` or `UNKNOWN`. Treat `INFERRED` and `UNKNOWN` as unverified — confirm in code before relying on them. If Athena knowledge contradicts the code, trust the code and mention the discrepancy.';
}

export function skipNote(): string {
  return 'For small, local changes (typos, copy, a rename inside one file) reading `rules.md` is enough — do not load every document.';
}

/** Full instruction body used by adapters. */
export function athenaInstructions(opts: { heading?: string; rulesImport?: string } = {}): string {
  return [
    `${opts.heading ?? '##'} Athena Project Intelligence`,
    '',
    'This project maintains structured project knowledge in `.athena/` (generated by Athena, curated by the developers).',
    '',
    opts.rulesImport ? `Project rules (always apply): ${opts.rulesImport}\n` : '',
    'Before making significant changes:',
    '',
    workflowSteps(),
    '',
    `${opts.heading ?? '##'}# Relevance map`,
    '',
    relevanceTable(),
    '',
    skipNote(),
    '',
    trustNote(),
  ]
    .filter((l, i, a) => !(l === '' && a[i - 1] === ''))
    .join('\n');
}
