import path from 'node:path';
import type { AgentAdapter, IntegrationCheck } from '../../core/agents/adapter.js';
import { readTextIfExists } from '../../core/util/fs.js';
import { athenaInstructions } from '../common/instructions.js';
import { OWNED_HEADER, planOwned, removeOwned, userEvidence } from '../common/files.js';

const RULE_FILE = '.windsurf/rules/athena.md';
/** Windsurf / Devin Desktop documents a 12,000 character limit per workspace rule file. */
export const WINDSURF_RULE_LIMIT = 12_000;

/**
 * Windsurf (renamed Devin Desktop on 2026-06-02), per
 * https://docs.devin.ai/desktop/cascade/memories (formerly docs.windsurf.com/windsurf/cascade/memories),
 * https://docs.devin.ai/desktop/devin-desktop-faq and https://docs.devin.ai/cli/extensibility/rules (checked 2026-09):
 * - rules: one Markdown file per workspace rule in `.devin/rules/` (preferred) or
 *   `.windsurf/rules/` (still read "for backward compatibility", side by side), max
 *   12,000 characters, activation via frontmatter `trigger: always_on | model_decision | glob | manual`.
 *   Athena writes `.windsurf/rules/athena.md`: it is read by Windsurf releases from before the
 *   rename, by Devin Desktop, and by the Devin Local agent / Devin CLI (which list
 *   `.windsurf/rules/*.md` among the rule files they read). Legacy `.windsurfrules` is still read.
 * - MCP: Cascade's `mcp_config.json` is per-user (outside the project), so Athena does not register
 *   itself; the docs describe no workspace-level MCP file for Windsurf/Cascade.
 * - hooks: Cascade hooks (`.devin/hooks.json`, legacy `.windsurf/hooks.json`) apply to the legacy
 *   Cascade agent only, which the FAQ says remained available "through July" 2026; the default
 *   Devin Local agent uses a different hook system. Athena does not install either, so activity
 *   from Windsurf is reported as unsupported.
 */
export const windsurfAdapter: AgentAdapter = {
  id: 'windsurf',
  displayName: 'Windsurf',
  capabilities: { instructionsFile: true, scopedRules: true, hooks: false, mcp: false },
  supportNote:
    'Uses an Athena-owned workspace rule at .windsurf/rules/athena.md (trigger: always_on), which Windsurf and Devin Desktop read. MCP is configured per user in Windsurf, so Athena does not register it: add `{ "mcpServers": { "athena": { "command": "athena", "args": ["mcp"] } } }` to your mcp_config.json yourself. No activity hooks.',
  async detectPresence(root) {
    const evidence = await userEvidence(root, { files: ['.windsurfrules'], dirs: ['.windsurf'], athenaOwned: await generatedByAthena(root, [RULE_FILE]) });
    return { detectedInProject: evidence.length > 0, evidence };
  },
  async plan(ctx) {
    const content = ['---', 'trigger: always_on', '---', OWNED_HEADER, '', athenaInstructions({ heading: '#' }), ''].join('\n');
    if (content.length > WINDSURF_RULE_LIMIT) throw new Error(`Windsurf rule exceeds ${WINDSURF_RULE_LIMIT} characters`);
    return [await planOwned(ctx.root, RULE_FILE, content)];
  },
  async remove(root) {
    return (await removeOwned(root, RULE_FILE)) ? [RULE_FILE] : [];
  },
  async check(root) {
    const text = await readTextIfExists(path.join(root, RULE_FILE));
    if (text === null) return [{ ok: false, level: 'warn', message: `Windsurf: ${RULE_FILE} not found` }];
    if (!text.includes('Generated by Athena')) return [{ ok: false, level: 'warn', message: `Windsurf: ${RULE_FILE} is a developer file, so Athena did not write its rule there` }];
    const checks: IntegrationCheck[] = [];
    if (text.length > WINDSURF_RULE_LIMIT) checks.push({ ok: false, level: 'error', message: `Windsurf: ${RULE_FILE} exceeds the 12,000 character rule limit` });
    else if (!/^---\r?\n[\s\S]*?trigger:\s*always_on[\s\S]*?\r?\n---/.test(text)) checks.push({ ok: false, level: 'warn', message: `Windsurf: ${RULE_FILE} frontmatter was modified (trigger is not always_on)` });
    else checks.push({ ok: true, level: 'ok', message: `Windsurf: ${RULE_FILE}` });
    return checks;
  },
};

/** Only paths that actually hold Athena's generated file count as Athena-owned; a developer file there is evidence. */
async function generatedByAthena(root: string, rels: string[]): Promise<string[]> {
  const out: string[] = [];
  for (const rel of rels) {
    const text = await readTextIfExists(path.join(root, rel)).catch(() => null);
    if (text?.includes('Generated by Athena')) out.push(rel);
  }
  return out;
}
