import { FAKE } from '../helpers.js';

const json = (v: unknown) => JSON.stringify(v, null, 2);

/** A project that exercises every detector (and its edge cases) at once. */
export function kitchenSink(): Record<string, string | Buffer> {
  const files: Record<string, string | Buffer> = {
    'package.json': json({
      name: 'sink',
      description: '  Kitchen sink  ',
      private: true,
      packageManager: 'pnpm@9.0.0',
      main: './dist/index.js',
      module: 'dist/index.mjs',
      bin: { sink: './bin/sink.js' },
      workspaces: ['apps/*', 'packages/*'],
      scripts: { dev: 'next dev', build: 'tsc', test: 'vitest run', lint: 'eslint .', 'db:migrate': 'prisma migrate', release: 'np', fmt: 'prettier -w .' },
      dependencies: { express: '5', fastify: '5', '@nestjs/common': '10', koa: '2', hono: '4', next: '15', mongoose: '8', helmet: '8', ioredis: '5', bullmq: '5', '@sentry/node': '8' },
      devDependencies: { vitest: '3', jest: '29', typescript: '5' },
    }),
    'pnpm-workspace.yaml': 'packages:\n  - "apps/*"\n  - "packages/*"\n',
    'turbo.json': '{}',
    'pnpm-lock.yaml': 'lockfileVersion: 9\n',
    'Makefile': '.PHONY: build\nbuild:\n\tgo build\ntest: build\n\tgo test\nVAR := 1\n',
    'justfile': 'default:\n  just --list\ndeploy:\n  ./deploy.sh\n',
    'tools/deep/nested/Makefile': 'ignored:\n\ttrue\n',
    'apps/web/package.json': json({ name: '@sink/web', dependencies: { next: '15', react: '19', '@sink/ui': '*' } }),
    'apps/web/app/api/users/route.ts': 'export async function GET() {}\nexport const POST = async () => {}\n',
    'apps/web/app/(group)/@slot/api/health/route.ts': 'export function GET() {}\n',
    'apps/web/pages/api/legacy/index.ts': 'export default function handler() {}\n',
    'apps/web/src/middleware.ts': 'export function middleware(req) { if (!req.cookies.session) return redirect("/login"); }\n',
    'apps/web/jest.config.js': 'module.exports = { collectCoverage: true, coverage: {} };\n',
    'apps/api/package.json': json({ name: '@sink/api', dependencies: { express: '5', '@prisma/client': '6', jsonwebtoken: '9', bcrypt: '5', zod: '3' } }),
    'apps/api/src/server.ts': [
      "import express from 'express';",
      'const app = express();',
      'const router = express.Router();',
      "app.get('/health', (req, res) => res.send('ok'));",
      "router.post('/payments/:id/refund', async (req, res) => {});",
      "app.all('*', h);",
      "app.get(`/tpl`, h);",
      "fastify.route({ method: 'put', url: '/fastify/route', handler });",
      'const secret = process.env.STRIPE_SECRET_KEY;',
      "const port = process.env['PORT'];",
      'const mode = process.env.NODE_ENV;',
      'const v = import.meta.env.VITE_API_URL;',
    ].join('\n'),
    'apps/api/src/nest.controller.ts': "import { Controller, Get, Post } from '@nestjs/common';\n@Controller('orders')\nexport class OrdersController {\n  @Get()\n  list() {}\n  @Post(':id/cancel')\n  cancel() {}\n}\n@Controller({ path: 'x' })\nexport class Skipped { @Get('y') y() {} }\n",
    'apps/api/src/koa.ts': "import Koa from 'koa';\nrouter.get('/koa', h);\n",
    'apps/api/src/hono.ts': "import { Hono } from 'hono';\nconst app = new Hono();\napp.get('/hono/:id', h);\n",
    'apps/api/src/fastify-server.ts': "import Fastify from 'fastify';\nconst fastify = Fastify();\nfastify.get('/fast', h);\n",
    'apps/api/src/broken.ts': 'app.get("/x", (req, res) => { ',
    'apps/api/src/server.test.ts': "import { it } from 'vitest';\napp.get('/not-a-route', h);\n",
    'apps/api/src/types.d.ts': "declare module 'x';\n",
    'apps/api/src/auth/jwt.ts': 'export enum Role { ADMIN, USER }\nexport type Permissions = string[];\nexport interface UserRole {}\n',
    'apps/api/src/models/user.ts': "import mongoose from 'mongoose';\nexport const User = mongoose.model('User', schema);\nexport const Post = model<IPost>('Post', postSchema);\n",
    'apps/api/src/config.ts': `export const stripe = "${FAKE.stripe}";\nexport const gh = "${FAKE.github}";\nexport const aws = "${FAKE.aws}";\n`,
    'apps/api/prisma/schema.prisma': [
      'datasource db {',
      '  provider = "postgresql"',
      '  url      = env("DATABASE_URL")',
      '}',
      'model User {',
      '  id       String @id @default(cuid())',
      '  tenantId String // tenant',
      '  email    String @unique',
      '  orders   Order[]',
      '  @@index([tenantId])',
      '}',
      'model Order {',
      '  id     String @id',
      '  userId String',
      '  user   User   @relation(fields: [userId], references: [id])',
      '}',
      'view Report {',
      '  id Int @unique',
      '}',
    ].join('\n'),
    'apps/api/prisma/migrations/20240101_init/migration.sql': 'CREATE TABLE "User" (id text);',
    'packages/ui/package.json': json({ name: '@sink/ui', dependencies: { react: '19' } }),
    'packages/ui/src/button.tsx': 'export const Button = () => null;',
    'packages/untested/package.json': json({ name: '@sink/untested' }),
    'packages/untested/src/index.ts': 'export const x = 1;',
    'packages/broken/package.json': '{ not json',
    'packages/nulljson/composer.json': '{"name": "acme/php", "require": {"php": ">=8", "laravel/framework": "11", "ext-json": "*"}, "require-dev": {"phpunit/phpunit": "10"}, "scripts": {"test": "phpunit"}}',
    '.env.example': 'DATABASE_URL=\nexport STRIPE_SECRET_KEY=\nPORT=3000\n',
    'config/.env.sample': 'REDIS_URL=\n',
    '.env': `STRIPE_SECRET_KEY=${FAKE.stripe}\n`,
    '.env.production': 'X=1\n',
    'Dockerfile': 'FROM --platform=linux/amd64 node:22-alpine AS build\nFROM node:22-alpine\nEXPOSE 3000 9229\nEXPOSE 3000\n',
    'services/worker/worker.dockerfile': 'FROM python:3.12\n',
    'docker-compose.yml': 'services:\n  api:\n    build: .\n    ports: ["3000:3000", {target: 80, published: 8080}]\n    depends_on: [db, cache]\n  db:\n    image: postgres:16\n  cache:\n    image: redis:7\n  mq:\n    image: rabbitmq:3\n  bad: 5\n',
    'compose.override.yaml': 'services: [unclosed',
    '.github/workflows/ci.yml': 'name: CI\non: push\njobs:\n  test:\n    name: Unit tests\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci\n      - run: |\n          npm test\n          npx semgrep --config auto\n  lint:\n    steps:\n      - run: npm run lint\n',
    '.github/workflows/broken.yml': 'jobs: [unclosed',
    '.github/workflows/empty.yml': '',
    '.github/dependabot.yml': 'version: 2',
    '.gitlab-ci.yml': 'stages: [test]\n.hidden:\n  script: echo hi\ntest:\n  script:\n    - npm test\n    - trivy fs .\nbuild:\n  script: make build\n',
    '.circleci/config.yml': 'version: 2.1\njobs:\n  build:\n    steps:\n      - checkout\n      - run: npm ci\n      - run:\n          command: npm test\n',
    'Jenkinsfile': "pipeline { stages { stage('Build') {} stage(\"Test\") {} } }\n",
    'ci/Jenkinsfile': 'pipeline {}\n',
    'azure-pipelines.yml': 'trigger: [main]\n',
    'k8s/deploy.yaml': 'apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: x\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: y\n---\napiVersion: v1\nkind: Deployment\n',
    'k8s/helm/templates/t.yaml': 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: {{ .Values.name }}\n  labels: {{ bad\n',
    'infra/main.tf': 'terraform {\n  required_providers {\n    aws = { source = "hashicorp/aws" }\n    google = { source = "google" }\n  }\n}\nprovider "aws" {\n}\nprovider "cloudflare" {\n}\n',
    'vercel.json': '{}',
    'fly.toml': 'app = "x"\n',
    'template.yaml': 'AWSTemplateFormatVersion: x\n',
    'Chart.yaml': 'name: c\n',
    'nginx/site.conf': 'server {}\n',
    'renovate.json': '{}',
    'SECURITY.md': '# Security\n',
    'openapi.yaml': 'openapi: 3.0.0\n',
    'schema.graphql': 'type Query { x: Int }\n',
    'api.proto': 'syntax = "proto3";\n',
    // Python
    'py/pyproject.toml': '[project]\nname = "pysvc"\nversion = "1.0"\ndependencies = ["fastapi>=0.110", "SQLAlchemy[asyncio]", "Flask", "django"]\n[project.optional-dependencies]\ndev = ["pytest"]\n[project.scripts]\nserve = "pysvc:main"\n[tool.uv.workspace]\nmembers = ["libs/*"]\n',
    'py/requirements-dev.txt': '# dev\npytest==8\n-r base.txt\nblack\n',
    'py/Pipfile': '[packages]\nrequests = "*"\n[dev-packages]\nPytest = "*"\n',
    'py/app/main.py': 'from fastapi import FastAPI\napp = FastAPI()\n@app.get("/items/{id}")\ndef read(id): ...\n@router.api_route("/multi", methods=["GET", "POST"])\ndef multi(): ...\n@bp.route("/flask")\ndef f(): ...\nimport os\nos.environ.get("DATABASE_URL")\nos.getenv("PY_SECRET_TOKEN")\n',
    'py/app/models.py': 'class Item(Base):\n    __tablename__ = "items"\n    id = Column(Integer)\n    name: Mapped[str] = mapped_column(String)\n\nclass Hero(SQLModel, table=True):\n    id: int = Field(primary_key=True)\n',
    'py/shop/urls.py': 'urlpatterns = [\n    path("products/", views.list),\n    re_path(r"^legacy/$", views.legacy),\n]\n',
    'py/shop/models.py': 'from django.db import models\n\nclass Product(models.Model):\n    name = models.CharField(max_length=10)\n    owner = models.ForeignKey("auth.User", on_delete=models.CASCADE)\n\nclass Role(models.Model):\n    label = models.CharField()\n',
    'py/shop/migrations/0001_initial.py': '',
    'py/conftest.py': '',
    'py/tests/test_main.py': 'def test_x(): pass\n',
    'py/alembic/versions/abc_init.py': '',
    // Go / Rust / Java / C# / Ruby / PHP / Dart / Elixir / Gradle
    'go/go.mod': 'module example.com/svc\n\ngo 1.23\n\nrequire (\n\tgithub.com/gin-gonic/gin v1.10.0\n\tgorm.io/gorm v1.25.0\n)\nrequire github.com/lib/pq v1.10.0\n',
    'go/go.work': 'go 1.23\nuse (\n\t./a\n\t./b\n)\nuse ./c\n',
    'go/cmd/server/main.go': 'package main\nfunc main() {\n r.GET("/ping", h)\n mux.HandleFunc("POST /v1/users", h)\n mux.Handle("/static", h)\n mux.HandleFunc("noslash", h)\n e.Get("/echo", h)\n os.Getenv("GO_VAR")\n}\n',
    'go/cmd/server/main_test.go': 'package main\n r.GET("/nope", h)\n',
    'rust/Cargo.toml': '[workspace]\nmembers = ["crates/*"]\n',
    'rust/crates/core/Cargo.toml': '[package]\nname = "core"\nversion = "0.1.0"\n[dependencies]\naxum = "0.7"\nsqlx = "0.8"\nactix-web = "4"\n[dev-dependencies]\ntokio = "1"\n',
    'rust/crates/core/src/main.rs': 'let app = Router::new().route("/users", get(list)).route("/x", post(y));\n#[get("/actix")]\nasync fn a() {}\n#[tokio::test]\nasync fn t() {}\nlet v = env::var("RUST_VAR");\n',
    'rust/crates/core/src/lib.rs': 'pub fn x() {}\n',
    'java/pom.xml': '<project><parent><artifactId>parent</artifactId></parent><artifactId>billing</artifactId><modules><module>core</module></modules><dependencies><dependency><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency></dependencies></project>',
    'java/src/main/java/BillingController.java': '@RestController\n@RequestMapping("/api/billing")\npublic class BillingController {\n  @GetMapping("/invoices")\n  public List<Invoice> list() {}\n  @PostMapping(value = "/pay")\n  public void pay() {}\n  @DeleteMapping\n  public void del() {}\n  String k = System.getenv("JAVA_VAR");\n}\n',
    'java/src/main/java/BillingApplication.java': 'class BillingApplication {}\n',
    'kt/build.gradle.kts': 'dependencies {\n  implementation("org.springframework.boot:spring-boot-starter-web:3.0.0")\n  testImplementation("org.junit.jupiter:junit-jupiter:5.0")\n}\n',
    'kt/settings.gradle.kts': 'rootProject.name = "kt"\ninclude(":app", ":lib:core")\n',
    'dotnet/Api.csproj': '<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><PackageReference Include="Serilog" /></ItemGroup></Project>',
    'dotnet/Tests.csproj': '<Project><ItemGroup><PackageReference Include="xunit" /></ItemGroup></Project>',
    'dotnet/Program.cs': 'app.MapGet("/minimal", () => 1);\nvar s = Environment.GetEnvironmentVariable("CS_VAR");\n',
    'dotnet/Controllers/UsersController.cs': '[Route("api/users")]\n[ApiController]\npublic class UsersController {\n  [HttpGet]\n  public void List() {}\n  [HttpPost("{id}")]\n  public void Create() {}\n}\n',
    'ruby/Gemfile': 'source "https://rubygems.org"\ngem "rails"\ngroup :development, :test do\n  gem "rspec-rails"\nend\ngem "devise"\n',
    'config/routes.rb': 'Rails.application.routes.draw do\n  get "/about", to: "pages#about"\n  post "login", to: "s#c"\n  resources :articles\n  resource :profile\nend\n',
    'app/models/user_role.rb': 'class UserRole < ApplicationRecord\n role = ENV["RB_VAR"]\nend\n',
    'routes/web.php': "<?php\nRoute::get('/', fn() => 1);\nRoute::resource('photos', C::class);\n$x = env('PHP_VAR');\n",
    'lib/main.dart': "const x = String.fromEnvironment('DART_VAR');\n",
    'pubspec.yaml': 'name: app\ndependencies:\n  flutter: {sdk: flutter}\ndev_dependencies:\n  flutter_test: {sdk: flutter}\n',
    'mix.exs': 'def project do [app: :myapp] end\ndefp deps do [{:phoenix, "~> 1.7"}, {:ecto, "~> 3.0"}] end\n',
    'db/migrations/001_init.sql': '-- comment\nCREATE TABLE IF NOT EXISTS invoices (\n  id BIGINT PRIMARY KEY,\n  customer_id BIGINT NOT NULL REFERENCES customers(id),\n  amount NUMERIC(10,2),\n  CONSTRAINT fk FOREIGN KEY (customer_id) REFERENCES customers(id),\n  UNIQUE (id)\n);\nCREATE UNIQUE INDEX invoices_customer ON invoices (customer_id);\n/* block */\nCREATE TABLE roles (id int);\n',
    'db/migrations/002_more.sql': 'CREATE INDEX CONCURRENTLY idx_amount ON invoices USING btree (amount);\nCREATE TABLE invoices (id int, note text UNIQUE);\nCREATE INDEX idx_note ON invoices(note);\nCREATE INDEX idx_missing ON nowhere(x);\n',
    'db/migrate/20240101_create.rb': 'class Create < ActiveRecord::Migration; end\n',
    'supabase/migrations/1_init.sql': 'CREATE TABLE "public"."profiles" (id uuid);\n',
    'src/index.ts': 'export {}\n',
    'src/cli.ts': 'export {}\n',
    'src/lib.rs': 'fn main() {}\n',
    'examples/app.ts': 'export {}\n',
    'test/helpers/util.ts': 'process.env.TEST_ONLY_VAR;\n',
    'e2e/login.spec.ts': 'test("x", () => {});\n',
    'playwright.config.ts': 'export default {}\n',
    'vitest.config.ts': 'export default { test: { coverage: { provider: "v8" } } }\n',
    '.nycrc': '{}',
    'codecov.yml': 'coverage: {}\n',
    'README.md': '# Sink\n',
    'docs/empty.txt': '',
    'package-lock.json': `{"secret": "${FAKE.stripe}"}`,
    'public/app.min.js': `var k="${FAKE.github}";`,
    'assets/logo.png': Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x00, 0x00, 0x01, 0x02]),
    'assets/fake.ts': Buffer.from([0x65, 0x78, 0x00, 0x70]),
    'certs/key.pem': FAKE.pem,
    'deploy/values.yaml': `password: "${FAKE.dbPassword}"\napi_key: "zX9kLm2Pq8Rt4Vw6Yb1Nc3"\n`,
  };
  // Enough role definitions to hit the evidence cap, spread over several files.
  for (let i = 0; i < 6; i++) files[`apps/api/src/roles/r${i}.ts`] = `export enum Tier${i}Role { A }\nexport class Admin${i}Permission {}\n// role\n`;
  // An oversized file (metadata only) and an unreadable-as-text binary.
  files['assets/huge.sql'] = `CREATE TABLE huge (id int);\n${'-- pad\n'.repeat(200_000)}`;
  return files;
}

/** Many secrets across many files: exercises the 500-finding cap and its warning. */
export function manySecrets(): Record<string, string> {
  const files: Record<string, string> = { 'package.json': json({ name: 'leaky' }) };
  for (let i = 0; i < 60; i++) files[`src/leak${String(i).padStart(3, '0')}.ts`] = Array.from({ length: 10 }, (_, k) => `export const k${k} = "${FAKE.aws.slice(0, -2)}${String(k).padStart(2, '0')}";`).join('\n');
  return files;
}
