import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { AgentAdapter, IntegrationCheck } from '../../core/agents/adapter.js';
import { readTextIfExists } from '../../core/util/fs.js';
import { athenaInstructions } from '../common/instructions.js';
import { OWNED_HEADER, planOwned, removeOwned, userEvidence } from '../common/files.js';

const RULES_DIR = '.clinerules';
const RULE_FILE = '.clinerules/athena.md';
/** Used only when `.clinerules` is a single file, so no directory can be created there. */
const ALT_RULE_FILE = '.cline/rules/athena.md';

/**
 * Cline (VS Code / JetBrains extension, CLI, SDK), per https://docs.cline.bot/customization/cline-rules,
 * https://docs.cline.bot/getting-started/config, https://docs.cline.bot/mcp/mcp-overview and
 * https://docs.cline.bot/customization/plugins (checked 2026-09):
 * - rules: Markdown files in `.clinerules/` or `.cline/rules/` at the project root; "Both directories
 *   are searched when present". Files without frontmatter are always active; each rule can be
 *   toggled in the Rules panel and is enabled by default. Athena writes `.clinerules/athena.md`
 *   (the directory the Rules panel itself uses). If `.clinerules` is a single file (the older
 *   format), Athena leaves it untouched and writes `.cline/rules/athena.md` instead.
 * - MCP: servers live in the extension's MCP settings / `~/.cline/…` (per user), so Athena does
 *   not register itself.
 * - hooks: the Hooks page defers to SDK plugins (TypeScript modules, "not applicable on VSCode and
 *   JetBrains Extension"); `.cline/hooks/` is listed in the config layout but its format is not
 *   documented. Athena installs no hooks, so Cline activity is reported as unsupported.
 */
export const clineAdapter: AgentAdapter = {
  id: 'cline',
  displayName: 'Cline',
  capabilities: { instructionsFile: true, scopedRules: true, hooks: false, mcp: false },
  supportNote:
    'Uses an Athena-owned workspace rule at .clinerules/athena.md (or .cline/rules/athena.md when .clinerules is a single file). MCP servers are configured per user in Cline, so Athena does not register it: add an "athena" server with command `athena` and args ["mcp"] in Cline\'s MCP settings yourself. No activity hooks.',
  async detectPresence(root) {
    const evidence = await userEvidence(root, { files: [RULES_DIR], dirs: [RULES_DIR, '.cline'], athenaOwned: await generatedByAthena(root, [RULE_FILE, ALT_RULE_FILE]) });
    return { detectedInProject: evidence.length > 0, evidence };
  },
  async plan(ctx) {
    const content = [OWNED_HEADER, '', athenaInstructions({ heading: '#' }), ''].join('\n');
    return [await planOwned(ctx.root, await rulePath(ctx.root), content)];
  },
  async remove(root) {
    const touched: string[] = [];
    for (const rel of [RULE_FILE, ALT_RULE_FILE]) {
      if (!(await isDirectory(path.join(root, path.dirname(rel))))) continue;
      if (await removeOwned(root, rel)) touched.push(rel);
    }
    return touched;
  },
  async check(root) {
    const rel = await rulePath(root);
    const text = await readTextIfExists(path.join(root, rel));
    if (text === null) return [{ ok: false, level: 'warn', message: `Cline: ${rel} not found` }];
    if (!text.includes('Generated by Athena')) return [{ ok: false, level: 'warn', message: `Cline: ${rel} is a developer file, so Athena did not write its rule there` }];
    const checks: IntegrationCheck[] = [{ ok: true, level: 'ok', message: `Cline: ${rel}` }];
    if (rel === ALT_RULE_FILE && !(await isDirectory(path.join(root, RULES_DIR))) && (await exists(path.join(root, RULES_DIR)))) {
      checks.push({ ok: true, level: 'warn', message: `Cline: .clinerules is a single file, so Athena's rule is in ${ALT_RULE_FILE}; older Cline versions that only read .clinerules will not see it` });
    }
    return checks;
  },
};

/** `.clinerules/athena.md`, unless `.clinerules` is a file or Athena already owns the `.cline/rules/` fallback. */
async function rulePath(root: string): Promise<string> {
  const clinerules = path.join(root, RULES_DIR);
  if ((await exists(clinerules)) && !(await isDirectory(clinerules))) return ALT_RULE_FILE;
  const alt = await readTextIfExists(path.join(root, ALT_RULE_FILE)).catch(() => null);
  if (alt?.includes('Generated by Athena')) return ALT_RULE_FILE;
  return RULE_FILE;
}

async function exists(p: string): Promise<boolean> {
  return (await fs.lstat(p).catch(() => null)) !== null;
}

async function isDirectory(p: string): Promise<boolean> {
  return (await fs.lstat(p).catch(() => null))?.isDirectory() ?? false;
}

/** Only paths that actually hold Athena's generated file count as Athena-owned; a developer file there is evidence. */
async function generatedByAthena(root: string, rels: string[]): Promise<string[]> {
  const out: string[] = [];
  for (const rel of rels) {
    const text = await readTextIfExists(path.join(root, rel)).catch(() => null);
    if (text?.includes('Generated by Athena')) out.push(rel);
  }
  return out;
}
