import type { Severity } from '../findings/finding.js';
import {
  coverageGaps,
  DISPLAY_ORDER,
  displayTitle,
  engineText,
  plural,
  scopeText,
  sortForDisplay,
  statusKind,
  statusOf,
  summarize,
  uncoveredCategories,
  whereOf,
  type ReportInput,
} from './shared.js';

/** Hidden marker identifying Athena's scan comment, so CI can update it in place. */
export const SCAN_MARKER = '<!-- athena-scan:v1 -->';
export const MAX_MARKDOWN_FINDINGS = 50;
const MAX_CELL = 200;

const SEV_LABEL: Record<Severity, string> = { critical: 'Critical', high: 'High', unrated: 'Unrated', medium: 'Medium', low: 'Low', info: 'Info' };

/**
 * Inline Markdown text from untrusted input (titles and messages come from tools and
 * from the scanned code): one line, no HTML, no Markdown syntax, no table breaks, no
 * @-mentions, bounded length.
 */
export function mdText(s: string, max = MAX_CELL): string {
  // eslint-disable-next-line no-control-regex
  let t = String(s).replace(/[\r\n\t\x00-\x1f\x7f]+/g, ' ').trim();
  if ([...t].length > max) t = `${[...t].slice(0, max - 1).join('')}…`;
  return t
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/[\\`*_[\]|~]/g, (ch) => `\\${ch}`)
    // Block syntax only matters at the start (headings, list items inside a list item).
    .replace(/^([#+=-])/, '\\$1')
    .replace(/^(\d+)([.)])/, '$1\\$2')
    .replace(/@/g, '@\u200b');
}

/** A path or id as inline code. `inTable` escapes `|`, which GFM tables split on even inside code spans. */
export function mdCode(s: string, inTable = false): string {
  // eslint-disable-next-line no-control-regex
  let t = String(s).replace(/[\r\n\x00-\x1f\x7f`]+/g, '');
  if ([...t].length > MAX_CELL) t = `${[...t].slice(0, MAX_CELL - 1).join('')}…`;
  if (inTable) t = t.replace(/\|/g, '\\|');
  return t ? `\`${t}\`` : '';
}

export function renderMarkdown(input: ReportInput): string {
  const r = input.result;
  const s = summarize(input);
  const lines: string[] = [SCAN_MARKER, '### Athena scan', ''];

  lines.push(`Scope: ${mdCode(scopeText(r))} · ${plural(s.open, 'open finding')}${s.openPotential ? ` (${s.openPotential} potential)` : ''}`, '');

  if (input.gate) {
    lines.push(`**Gate: ${input.gate.passed ? 'passed' : 'failed'}**`);
    for (const reason of input.gate.reasons) lines.push(`- ${mdText(reason)}`);
    lines.push('');
  }

  if (s.open) {
    lines.push('| Severity | Open |', '| --- | ---: |');
    for (const sev of DISPLAY_ORDER) if (s.openBySeverity[sev]) lines.push(`| ${SEV_LABEL[sev]} | ${s.openBySeverity[sev]} |`);
    lines.push('');
  } else lines.push('No open findings.', '');

  const hidden = (['baselined', 'suppressed', 'triaged', 'excluded'] as const).filter((k) => s[k] > 0).map((k) => `${s[k]} ${k}`);
  if (hidden.length) lines.push(`Not counted: ${hidden.join(', ')}.`, '');

  const open = sortForDisplay(r.findings).filter((f) => statusKind(statusOf(input, f)) === 'open');
  if (open.length) {
    const shown = open.slice(0, MAX_MARKDOWN_FINDINGS);
    lines.push('#### Open findings', '', '| Severity | Finding | Location | Rule | Source |', '| --- | --- | --- | --- | --- |');
    for (const f of shown) {
      lines.push(`| ${SEV_LABEL[f.severity]} | ${mdText(displayTitle(f))} | ${mdCode(whereOf(f, input.root), true)} | ${mdCode(f.ruleId, true)} | ${f.label} · ${mdText(engineText(f))} |`);
    }
    lines.push('');
    if (open.length > shown.length) lines.push(`_Showing ${shown.length} of ${open.length} open findings; ${open.length - shown.length} more not shown. Run \`athena scan\` for the full list._`, '');
  }

  const ratings = Object.entries(input.ratings ?? {}).filter(([, v]) => v);
  if (ratings.length) {
    lines.push('#### Ratings', '', '| Category | Grade | Basis |', '| --- | :---: | --- |');
    for (const [cat, rating] of ratings) lines.push(`| ${mdText(cat)} | ${rating!.grade} | ${mdText(rating!.basis)} |`);
    lines.push('');
  }

  // Coverage gaps: always stated, including "none".
  const gaps = coverageGaps(r.coverage);
  const uncovered = uncoveredCategories(r.coverage);
  lines.push('#### Coverage', '');
  if (!r.coverage.length) lines.push('- **No engine reported coverage: nothing was checked.**');
  for (const g of gaps) lines.push(`- ${mdCode(g.engine)} (${mdText(g.category)}${g.target ? `, ${mdCode(g.target)}` : ''}): **${g.status}**${g.reason ? ` — ${mdText(g.reason)}` : ''}`);
  if (r.coverage.length && !gaps.length) lines.push(`- All ${plural(r.coverage.length, 'engine')} ran cleanly.`);
  const network = r.coverage.filter((c) => c.network).map((c) => mdCode(c.engine));
  if (network.length) lines.push(`- Used the network: ${network.join(', ')}.`);
  if (uncovered.length) lines.push(`- Not covered by any engine: ${uncovered.join(', ')}.`);
  lines.push('');

  lines.push(
    `<sub>Generated by <a href="https://athena.sabari.me">Athena</a> ${mdText(input.toolVersion, 40)}. Findings show a type and location only, never a matched value. “Potential” findings are heuristics: check them.</sub>`,
  );
  return `${lines.join('\n')}\n`;
}
